DROP TABLE IF EXISTS process_execution CASCADE;
DROP TABLE IF EXISTS operation_log CASCADE;
DROP TABLE IF EXISTS schedule CASCADE;
DROP TABLE IF EXISTS assignment CASCADE;
DROP TABLE IF EXISTS task CASCADE;
DROP TABLE IF EXISTS service CASCADE;